Update ChargebackResponse.cs
Viincenttt/MollieApi pull request #225
Opened 2021-02-25 16:45 UTC by Sippelberg

Added the ChargebackResponseReason parameter to the ChargebackResponse Class

2021-03-14 08:05 UTC, Viincenttt commented
Not sure how this code would work. I can see in the Mollie documentation that there is a reason property, however, it's name is "reason" and it's not of the type ChargebackResponse

2021-03-15 09:55 UTC, Sippelberg commented
Hey Viincenttt,
Thanks you very much for the reply.

Since the costs may vary if a chargeback is for example of the type MD06 (€7.5) or MS03(€0.05), and I want to be able to charge these costs to my customer I need to know the response reason.

The Mollie ChargebackResponse object in JSON contains:
      "reason": {
          "code": "MD06",
          "description": "Return of funds requested by end customer"
      },

OR
    
      "reason": {
          "code": "MS03",
          "description": "Reason not specified"
      },

In the code I would use it like this:

ListResponse <ChargebackResponse> myChargebacks = await MollieData.TryGetChargebacks(aTransactie.MollieId);

foreach ( var myChB in myChargebacks.Items ) {
    if (myChB.Reason != null ) {
        mybedrag = mybedrag + SDD_codes.RetrieveForCode(myChB.Reason.code).kosten;
    }
}

In the example I get the costs for the chargeback from a local table "SDD_codes" since Mollie hasn't provided us with an endpoint to get the fees. I opened a support question and they are looking into it but I'm not quite sure if or when they will provide this endpoint.

2021-04-24 07:31 UTC, Viincenttt requested changes

2021-04-24 07:31 UTC, Viincenttt commented on Mollie.Api/Models/Chargeback/ChargebackResponse.cs
> +        public ChargebackResponse ChargebackResponseReason { get; set; }
This property should be of type `ChargebackResponseReason` not `ChargebackResponse` right?

2021-04-24 07:31 UTC, Viincenttt commented on Mollie.Api/Models/Chargeback/ChargebackResponse.cs
> +	public string PaymentId { get; set; }
Can you fix the spacing issues in this file? :)

2021-05-17 14:57 UTC, Sippelberg reviewed
issues (spacing, ChargebackResponseReason) were resolved

2021-05-20 20:52 UTC, Viincenttt approved these changes
Thanks for making the adjustments!

2021-05-20 20:53 UTC, merged